resources:
  - name: apps-test-ecr
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: PP-7683-apps-test-ecr
      paths:
        - ci/pipelines/apps-test-ecr.yml
  # Github Releases
  - name: git-app-pre-release
    type: git
    icon: github
    source: &github-release-source
      uri: https://github.com/alphagov/pay-toolbox
      branch: master
      tag_regex: "alpha_release-(.*)"
  # ECR registry resource
  - name: ecr-registry-test
    type: dev-registry-image
    icon: docker
    source:
      repository: govukpay/toolbox
      aws_access_key_id: ((readonly_access_key_id))
      aws_secret_access_key: ((readonly_secret_access_key))
      aws_session_token: ((readonly_session_token))
      # Need to create the role for the concourse user to assume in the test account
      aws_role_arn: arn:aws:iam::((pay_aws_test_account_id)):role/concourse
      # Hardcode the test account registry ID for now. Needs to be a string, not a number
      aws_ecr_registry_id: "((pay_aws_test_account_id))"
      aws_region: eu-west-1

resource_types:
  # Custom resource type - this has been merged to the
  # https://github.com/concourse/registry-image-resource repo,
  # however is not yet in a stable release. Using this custom
  # resource type allows us to support the ECR registry_id parameter
  # This can be removed once registry_id is in stable release of 'registry-image'.
  - name: dev-registry-image
    type: registry-image
    source:
      repository: concourse/registry-image-resource
      username: ((docker-username))
      password: ((docker-password))
      tag: dev

groups:
  - name: pipeline-meta-update
    jobs:
      - update-toolbox-test-ecr-pipeline
  - name: toolbox
    jobs:
      - toolbox-image-to-test-ecr
  - name: frontend
    jobs:
      - frontend-image-to-test-ecr
  - name: adminusers
    jobs:
      - adminusers-image-to-test-ecr
  - name: cardid
    jobs:
      - cardid-image-to-test-ecr
  - name: connector
    jobs:
      - connector-image-to-test-ecr
  - name: ledger
    jobs:
      - ledger-image-to-test-ecr
  - name: products
    jobs:
      - products-image-to-test-ecr
  - name: products-ui
    jobs:
      - products-ui-image-to-test-ecr
  - name: publicapi
    jobs:
      - publicapi-image-to-test-ecr
  - name: publicauth
    jobs:
      - publicauth-image-to-test-ecr
  - name: selfservice
    jobs:
      - selfservice-image-to-test-ecr

definitions:
  - &pull-image-from-dockerhub
    task: pull-image-from-dockerhub
    privileged: true
    file: toolbox-test-ecr/ci/tasks/pull-image-from-dockerhub.yml
    params:
      DOCKER_USERNAME: updateThisValue
      DOCKER_AUTH_TOKEN: updateThisValue
      DOCKER_REPOSITORY: updateThisValue
  - &put-ecr-registry-test
    put: ecr-registry-test
    params:
      image: image/image.tar
      additional_tags: git-app-pre-release/.git/HEAD

docker_credentials: &docker_credentials
  DOCKER_USERNAME: ((docker-username))
  DOCKER_AUTH_TOKEN: ((docker-password))

jobs:
  - name: update-apps-test-ecr-pipeline
    plan:
      - get: apps-test-ecr
        trigger: true
      - set_pipeline: apps-test-ecr
        file: apps-test-ecr/ci/pipelines/apps-test-ecr.yml
  - name: toolbox-test-ecr
    plan:
      - get: toolbox-test-ecr
      - get: git-app-pre-release
        trigger: true
      # Temporarily fetch image from Dockerhub until Concourse can build its own
      - <<: *pull-image-from-dockerhub
        params:
          DOCKER_REPOSITORY: govukpay/toolbox
          <<: *docker_credentials
      - <<: *put-ecr-registry-test
  - name: frontend-image-to-test-ecr
    plan:
      - get: toolbox-test-ecr
      - get: git-app-pre-release
        trigger: true
      # Temporarily fetch image from Dockerhub until Concourse can build its own
      - <<: *pull-image-from-dockerhub
        params:
          DOCKER_REPOSITORY: govukpay/frontend
          <<: *docker_credentials
      - <<: *put-ecr-registry-test
  - name: adminusers-image-to-test-ecr
    plan:
      - get: toolbox-test-ecr
      - get: git-app-pre-release
        trigger: true
      # Temporarily fetch image from Dockerhub until Concourse can build its own
      - <<: *pull-image-from-dockerhub
        params:
          DOCKER_REPOSITORY: govukpay/adminusers
          <<: *docker_credentials
      - <<: *put-ecr-registry-test
  - name: cardid-image-to-test-ecr
    plan:
      - get: toolbox-test-ecr
      - get: git-app-pre-release
        trigger: true
      # Temporarily fetch image from Dockerhub until Concourse can build its own
      - <<: *pull-image-from-dockerhub
        params:
          DOCKER_REPOSITORY: govukpay/cardid
          <<: *docker_credentials
      - <<: *put-ecr-registry-test
  - name: connector-image-to-test-ecr
    plan:
      - get: toolbox-test-ecr
      - get: git-app-pre-release
        trigger: true
      # Temporarily fetch image from Dockerhub until Concourse can build its own
      - <<: *pull-image-from-dockerhub
        params:
          DOCKER_REPOSITORY: govukpay/connector
          <<: *docker_credentials
      - <<: *put-ecr-registry-test
  - name: ledger-image-to-test-ecr
    plan:
      - get: toolbox-test-ecr
      - get: git-app-pre-release
        trigger: true
      # Temporarily fetch image from Dockerhub until Concourse can build its own
      - <<: *pull-image-from-dockerhub
        params:
          DOCKER_REPOSITORY: govukpay/ledger
          <<: *docker_credentials
      - <<: *put-ecr-registry-test
  - name: products-image-to-test-ecr
    plan:
      - get: toolbox-test-ecr
      - get: git-app-pre-release
        trigger: true
      # Temporarily fetch image from Dockerhub until Concourse can build its own
      - <<: *pull-image-from-dockerhub
        params:
          DOCKER_REPOSITORY: govukpay/products
          <<: *docker_credentials
      - <<: *put-ecr-registry-test
  - name: products-ui-image-to-test-ecr
    plan:
      - get: toolbox-test-ecr
      - get: git-app-pre-release
        trigger: true
      # Temporarily fetch image from Dockerhub until Concourse can build its own
      - <<: *pull-image-from-dockerhub
        params:
          DOCKER_REPOSITORY: govukpay/products-ui
          <<: *docker_credentials
      - <<: *put-ecr-registry-test
  - name: publicapi-image-to-test-ecr
    plan:
      - get: toolbox-test-ecr
      - get: git-app-pre-release
        trigger: true
      # Temporarily fetch image from Dockerhub until Concourse can build its own
      - <<: *pull-image-from-dockerhub
        params:
          DOCKER_REPOSITORY: govukpay/publicapi
          <<: *docker_credentials
      - <<: *put-ecr-registry-test
  - name: publicauth-image-to-test-ecr
    plan:
      - get: toolbox-test-ecr
      - get: git-app-pre-release
        trigger: true
      # Temporarily fetch image from Dockerhub until Concourse can build its own
      - <<: *pull-image-from-dockerhub
        params:
          DOCKER_REPOSITORY: govukpay/publicauth
          <<: *docker_credentials
      - <<: *put-ecr-registry-test
  - name: selfservice-image-to-test-ecr
    plan:
      - get: toolbox-test-ecr
      - get: git-app-pre-release
        trigger: true
      # Temporarily fetch image from Dockerhub until Concourse can build its own
      - <<: *pull-image-from-dockerhub
        params:
          DOCKER_REPOSITORY: govukpay/selfservice
          <<: *docker_credentials
      - <<: *put-ecr-registry-test
