resources:
  - name: pay-java-lambdas
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-java-lambdas
      branch: main
      username: alphagov-pay-ci-concourse
      password: ((github-access-token))
  - name: ci
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: main
      username: alphagov-pay-ci-concourse
      password: ((github-access-token))

jobs:
  - name: build
    plan:
      - get: src
        resource: pay-java-lambdas
        trigger: true
      - get: ci
        trigger: false
      - task: build-java-lambdas
        file: ci/ci/tasks/build-java-lambdas.yml
#        TODO on_failure
#        TODO on_success
