resources:
  - name: pay-java-lambdas
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-java-lambdas
      branch: main
      username: alphagov-pay-ci-concourse
      password: ((github-access-token))
  - name: pay-ci
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
      username: alphagov-pay-ci-concourse
      password: ((github-access-token))

jobs:
  - name: build
    plan:
      - get: src
        resource: pay-java-lambdas
        trigger: true
      - get: pay-ci
        trigger: false
      - task: build-java-lambdas
        file: pay-ci/ci/tasks/build-java-lambdas.yml
#        TODO on_failure
#    TODO on_success:
#      put: slack-notification
#      params:
#        channel: '#govuk-pay-activity'
#        icon_emoji: ":fargate:"
#        username: pay-concourse
#        text: "((.:success_snippet)) \n\n
#              <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse build #$BUILD_NAME>"

