resources:
  - name: pay-ci
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
jobs:
  - name: run-smoke-tests
    plan:
    - get: pay-ci
    - task: assume-role
      file: pay-ci/ci/tasks/assume-role.yml
      params:
        AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/concourse
        AWS_ROLE_SESSION_NAME: terraform-test-assume-role
    - load_var: role
      file: assume-role/assume-role.json
      format: json
    - task: run-create-card-payment-smoke-test
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: amazon/aws-cli
        params:
          AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
          AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
          AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
          AWS_PAGER: ""
          AWS_REGION: "eu-west-1"
        run:
          path: aws
          args: [ 'synthetics', 'start-canary', '--name', 'make_card_payment' ]


