resources:
  - name: cardid-s3-pipeline-definition
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
      paths:
        - ci/pipelines/cardid-s3.yml
      username: alphagov-pay-ci-concourse
      password: ((github-access-token))
  - name: pay-ci
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
      username: alphagov-pay-ci-concourse
      password: ((github-access-token))

  # Github Releases
  - name: cardid-git-release
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-cardid
      branch: master
      username: alphagov-pay-ci-concourse
      password: ((github-access-token))

  # S3 buckets
  - name: worldpay-bin-ranges
    type: s3
    icon: file-delimited
    source:
      access_key_id: ((readonly_access_key_id))
      secret_access_key: ((readonly_secret_access_key))
      session_token: ((readonly_session_token))
      aws_role_arn: arn:aws:iam::424875624006:role/concourse-worker-promoted-bin-ranges-read-only-deploy
      region_name: eu-west-1
      private: true
      bucket: bin-ranges-promoted-deploy
      versioned_file: latest/worldpay-v3.csv

  - name: discover-bin-ranges
    type: s3
    icon: file-delimited
    source:
      access_key_id: ((readonly_access_key_id))
      secret_access_key: ((readonly_secret_access_key))
      session_token: ((readonly_session_token))
      aws_role_arn: arn:aws:iam::424875624006:role/concourse-worker-promoted-bin-ranges-read-only-deploy
      region_name: eu-west-1
      private: true
      bucket: bin-ranges-promoted-deploy
      versioned_file: latest/discover.csv

  - name: testcard-bin-ranges
    type: s3
    icon: file-delimited
    source:
      access_key_id: ((readonly_access_key_id))
      secret_access_key: ((readonly_secret_access_key))
      session_token: ((readonly_session_token))
      aws_role_arn: arn:aws:iam::424875624006:role/concourse-worker-promoted-bin-ranges-read-only-deploy
      region_name: eu-west-1
      private: true
      bucket: bin-ranges-promoted-deploy
      versioned_file: latest/test-cards.csv

groups:
  - name: cardid
    jobs:
      - trigger-cardid-release
  - name: update-cardid-s3-pipeline
    jobs:
      - update-cardid-s3-pipeline

jobs:
  - name: update-cardid-s3-pipeline
    plan:
      - get: cardid-s3-pipeline-definition
        trigger: true
      - set_pipeline: cardid-s3
        file: cardid-s3-pipeline-definition/ci/pipelines/cardid-s3.yml
  - name: trigger-cardid-release
    plan:
      - in_parallel:
        - get: pay-ci
        - get: worldpay-bin-ranges
          trigger: true
        - get: discover-bin-ranges
          trigger: true
        - get: testcard-bin-ranges
          trigger: true
        - get: cardid-git-release
      - task: trigger-cardid-release
        file: pay-ci/ci/tasks/github-trigger-workflow.yml
        input_mapping:
          src: cardid-git-release
        params:
          REPO: alphagov/pay-cardid
          WORKFLOW: ci-trigger-release.yml
          GITHUB_TOKEN: ((github-access-token))
