---
resources:
  - name: detect-secrets-pipeline
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
      paths:
        - ci/pipelines/detect-secrets.yml

  - name: detect-secrets-src
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
      paths:
        - ci/docker/detect-secrets/*

  - name: detect-secrets-registry-image
    type: registry-image
    icon: docker
    source:
      repository: governmentdigitalservice/pay-detect-secrets
      username: ((docker-username))
      password: ((docker-access-token))
      tag: latest

  - name: pay-ci
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master

jobs:
  - name: detect-secrets-src
    plan:
      - in_parallel:
          - get: detect-secrets-src
            trigger: true
          - get: pay-ci
      - task: generate-docker-creds-config
        file: pay-ci/ci/tasks/generate-docker-config-file.yml
        params:
          USERNAME: ((docker-username))
          PASSWORD: ((docker-access-token))
          EMAIL: ((docker-email))
      - task: build
        privileged: true
        params:
          CONTEXT: detect-secrets-src/ci/docker/detect-secrets
          DOCKER_CONFIG: docker_creds
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: detect-secrets-src
          outputs:
            - name: image
          run:
            path: build
      - put: detect-secrets-registry-image
        params: { image: image/image.tar }

  - name: update-detect-secrets-pipeline
    plan:
      - get: detect-secrets-pipeline
        trigger: true
      - set_pipeline: detect-secrets
        file: detect-secrets-pipeline/ci/pipelines/detect-secrets.yml
