---
resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

resources:
  - name: ci-docs
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
      paths:
        - docs

  - name: paas
    type: cf-cli
    icon: cloud-upload-outline
    source:
      api: https://api.london.cloud.service.gov.uk
      org: govuk-pay
      space: tools
      username: ((cf-username))
      password: ((cf-password))

jobs:
  - name: deploy
    serial: true
    plan:
      - get: ci-docs
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
          inputs:
            - name: ci-docs
          outputs:
            - name: ci-docs/docs/build
          caches:
            - path: ci-docs/docs/vendor
          run:
            dir: ci-docs/docs
            path: bash
            args:
              - -c
              - |
                set -o errexit -o nounset -o pipefail
                apt-get update && apt-get install -y nodejs npm
                gem install bundler
                bundle install --deployment
                bundle exec middleman build
      - put: paas
        params:
          command: push
          app_name: pay-ci-docs
          path: ci-docs/docs/build
          manifest: ci-docs/docs/manifest.yml
