---
resources:
  - name: node-runner-pipeline
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
      paths:
        - ci/pipelines/node-runner.yml

  - name: node-runner-src
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
      paths:
        - ci/docker/node-runner/*

  - name: node-runner-node18
    type: registry-image
    icon: docker
    source:
      repository: governmentdigitalservice/pay-node-runner
      username: ((docker-username))
      password: ((docker-access-token))
      tag: node18

  - name: pay-ci
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master

# Builds and pushes the node-runner Docker image used by various Concourse CI pipelines
jobs:
  - name: build-and-push
    plan:
      - in_parallel:
        - get: node-runner-src
          trigger: true
        - get: pay-ci
      - task: generate-docker-creds-config
        file: pay-ci/ci/tasks/generate-docker-config-file.yml
        params:
          USERNAME: ((docker-username))
          PASSWORD: ((docker-access-token))
          EMAIL: ((docker-email))
      - in_parallel:
        - task: build-node-18
          privileged: true
          output_mapping:
            image: node18-image
          params:
            CONTEXT: node-runner-src/ci/docker/node-runner
            DOCKER_CONFIG: docker_creds
          config:
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: concourse/oci-build-task
            inputs:
            - name: node-runner-src
            outputs:
            - name: image
            run:
              path: build
      - in_parallel:
        - do:
        - put: node-runner-node18
          params:
            image: node18-image/image.tar
          get_params:
            skip_download: true

  - name: update-node-runner-pipeline
    plan:
      - get: node-runner-pipeline
        trigger: true
      - set_pipeline: node-runner
        file: node-runner-pipeline/ci/pipelines/node-runner.yml
