---
resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

resources:
  - name: pact-broker-pipeline
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
      paths:
        - ci/pipelines/pact-broker.yml

  - name: pact-broker-manifest
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
      paths:
        - ci/pact_broker

  - name: paas
    type: cf-cli
    icon: cloud-upload-outline
    source:
      api: https://api.cloud.service.gov.uk
      org: govuk-pay
      space: build
      username: ((cf-username))
      password: ((cf-password))
      cf_cli_version: 7

jobs:
  - name: set-pipeline
    plan:
      - get: pact-broker-pipeline
        trigger: true
      - set_pipeline: pact-broker
        file: pact-broker-pipeline/ci/pipelines/pact-broker.yml
  
  - name: deploy-pact-broker
    serial: true
    plan:
      - get: pact-broker-manifest
        trigger: true
      - put: paas
        params:
          command: push
          app_name: pay-pact-broker
          manifest: pact-broker-manifest/ci/pact_broker/pay-pact-broker_manifest.yml
          vars:
            pact-broker-username: ((pact-broker-username))
            pact-broker-password: ((pact-broker-password))
