---
resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: pact-broker-pipeline
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
      paths:
        - ci/pipelines/pact-broker.yml

  - name: pact-broker-src
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
      paths:
        - ci/docker/pact-broker/*

  - name: pay-ci
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master

  - name: pay-infra
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-infra
      branch: master
      username: alphagov-pay-ci-concourse
      password: ((github-access-token))

  - name: pact-broker-ecr-registry-deploy
    type: registry-image
    icon: docker
    source:
      repository: govukpay/pact-broker
      aws_access_key_id: ((readonly_access_key_id))
      aws_secret_access_key: ((readonly_secret_access_key))
      aws_session_token: ((readonly_session_token))
      aws_role_arn: arn:aws:iam::((pay_aws_deploy_account_id)):role/concourse
      aws_ecr_registry_id: "((pay_aws_deploy_account_id))"
      aws_region: eu-west-1

  - name: slack-notification
    type: slack-notification
    source:
      url: https://hooks.slack.com/services/((slack-notification-secret))

jobs:
  - name: set-pipeline
    plan:
      - get: pact-broker-pipeline
        trigger: true
      - set_pipeline: pact-broker
        file: pact-broker-pipeline/ci/pipelines/pact-broker.yml

  - name: deploy-pact-broker
    plan:
      - get: pay-ci
      - get: pay-infra
      - get: pact-broker-ecr-registry-deploy
        passed: [build-and-push-pact-broker]
        trigger: true
      - task: assume-role
        file: pay-ci/ci/tasks/assume-role.yml
        params:
          AWS_ROLE_ARN: arn:aws:iam::((pay_aws_deploy_account_id)):role/pay-concourse-pact-broker-deploy-tooling
          AWS_ROLE_SESSION_NAME: terraform-deploy-assume-role
      - load_var: role
        file: assume-role/assume-role.json
        format: json
      - load_var: pactbroker_image_tag
        file: pact-broker-ecr-registry-deploy/tag
      - task: deploy-pact-broker
        file: pay-ci/ci/tasks/deploy-pact-broker.yml
        params:
          ACCOUNT: deploy
          ENVIRONMENT: deploy-tooling
          AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
          AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
          AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
          PACTBROKER_IMAGE_TAG: ((.:pactbroker_image_tag))
      - task: wait-for-deploy
        file: pay-ci/ci/tasks/wait-for-deploy.yml
        params:
          ACCOUNT: deploy
          APP_NAME: pactbroker
          ENVIRONMENT: deploy-tooling
          AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
          AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
          AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
    on_failure:
      put: slack-notification
      attempts: 10
      params:
        channel: "#govuk-pay-starling"
        silent: true
        text: ":red-circle: Failed to deploy pay-pact-broker image - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse build #$BUILD_NAME>"
        icon_emoji: ":concourse:"
        username: pay-concourse
    on_success:
      put: slack-notification
      attempts: 10
      params:
        channel: "#govuk-pay-activity"
        silent: true
        text: ":green-circle: Deployed pay-pact-broker image - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse build #$BUILD_NAME>"
        icon_emoji: ":concourse:"
        username: pay-concourse

  - name: build-and-push-pact-broker
    plan:
      - in_parallel:
        - get: pact-broker-src
          trigger: true
        - get: pay-ci
      - task: generate-docker-creds-config
        file: pay-ci/ci/tasks/generate-docker-config-file.yml
        params:
          USERNAME: ((docker-username))
          PASSWORD: ((docker-access-token))
          EMAIL: ((docker-email))
      - task: get-pact-broker-image-tag
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
              tag: latest
          inputs:
          - name: pact-broker-src
          outputs:
           - name: tags
          run:
            path: ash
            args:
              - -ec
              - |
                cat pact-broker-src/ci/docker/pact-broker/Dockerfile | grep -i FROM | head -n 1 | awk '{print $2;}' | cut -f 2 -d ":" | tee tags/tag
      - task: build-pact-broker-image
        privileged: true
        params:
          CONTEXT: pact-broker-src/ci/docker/pact-broker
          DOCKER_CONFIG: docker_creds
          UNPACK_ROOTFS: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: pact-broker-src
            - name: docker_creds
          outputs:
            - name: image
          run:
            path: build
      - put: pact-broker-ecr-registry-deploy
        params:
          image: image/image.tar
          additional_tags: tags/tag
        get_params:
          skip_download: true
    on_failure:
      put: slack-notification
      attempts: 10
      params:
        channel: "#govuk-pay-starling"
        silent: true
        text: ":red-circle: Failed to build and push pay-pact-broker image - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse build #$BUILD_NAME>"
        icon_emoji: ":concourse:"
        username: pay-concourse
    on_success:
      put: slack-notification
      attempts: 10
      params:
        channel: "#govuk-pay-activity"
        silent: true
        text: ":green-circle: Built and pushed pay-pact-broker image - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse build #$BUILD_NAME>"
        icon_emoji: ":concourse:"
        username: pay-concourse
