resources:
  # GitHub Repos
  - name: pay-js-pipeline-definition
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
      paths:
        - ci/pipelines/pay-js.yml
  - name: pay-ci
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
  - name: js-commons-git-release
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-js-commons
      branch: master
      commit_filter:
        exclude: [ "\\[automated release\\]" ]
  - name: js-metrics-git-release
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-js-metrics
      branch: main
      commit_filter:
        exclude: [ "\\[automated release\\]" ]

groups:
  - name: js-commons
    jobs:
      - version-and-push-commons
  - name: js-metrics
    jobs:
      - version-and-push-metrics
  - name: update-pay-js-pipeline
    jobs:
      - update-pay-js-pipeline

jobs:
  - name: version-and-push-metrics
    plan:
      - in_parallel:
        - get: js-metrics-git-release
          trigger: true
        - get: pay-ci
      - task: npm-version-and-create-pr
        file: pay-ci/ci/tasks/npm-version-and-create-pr.yml
        input_mapping:
          src: js-metrics-git-release
        params:
          BASE: main
          REPO: alphagov/pay-js-metrics
          GITHUB_TOKEN: ((github-access-token))
  - name: version-and-push-commons
    plan:
      - in_parallel:
        - get: js-commons-git-release
          trigger: true
        - get: pay-ci
      - task: npm-version-and-create-pr
        file: pay-ci/ci/tasks/npm-version-and-create-pr.yml
        input_mapping:
          src: js-commons-git-release
        params:
          BASE: master
          REPO: alphagov/pay-js-commons
          GITHUB_TOKEN: ((github-access-token))
  - name: update-pay-js-pipeline
    plan:
      - get: pay-js-pipeline-definition
        trigger: true
      - set_pipeline: pay-js
        file: pay-js-pipeline-definition/ci/pipelines/pay-js.yml
