---
definitions:
  aws_staging_config: &aws_staging_config
    aws_access_key_id: ((readonly_access_key_id))
    aws_secret_access_key: ((readonly_secret_access_key))
    aws_session_token: ((readonly_session_token))
    aws_role_arn: arn:aws:iam::((pay_aws_staging_account_id)):role/concourse
    aws_ecr_registry_id: "((pay_aws_staging_account_id))"
    aws_region: eu-west-1

  aws_deploy_config: &aws_deploy_config
    aws_access_key_id: ((readonly_access_key_id))
    aws_secret_access_key: ((readonly_secret_access_key))
    aws_session_token: ((readonly_session_token))
    aws_role_arn: arn:aws:iam::((pay_aws_deploy_account_id)):role/concourse
    aws_ecr_registry_id: "((pay_aws_deploy_account_id))"
    aws_region: eu-west-1

resources:
  - name: prometheus-pushgateway
    type: registry-image
    icon: docker
    check_every: 1h
    source:
      repository: prom/pushgateway
      tag: v1.6.0
      username: ((docker-username))
      password: ((docker-access-token))

  - name: ecr-prometheus-pushgateway
    type: registry-image
    icon: docker
    check_every: never
    source:
      repository: pushgateway
      tag: v1.6.0
      <<: *aws_deploy_config

  - name: adot-ecr-registry-staging
    type: registry-image
    icon: docker
    source:
      repository: govukpay/adot
      variant: release
      <<: *aws_staging_config

  - name: adot-ecr-registry-deploy
    type: registry-image
    icon: docker
    source:
      repository: govukpay/adot
      variant: release
      <<: *aws_deploy_config

  - name: slack-notification
    type: slack-notification
    source:
      url: https://hooks.slack.com/services/((slack-notification-secret))

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

jobs:
  - name: push-adot-to-deploy-ecr
    plan:
      - get: adot-ecr-registry-staging
        params:
          format: oci
        trigger: true
      - load_var: application_image_tag
        file: adot-ecr-registry-staging/tag
      - put: adot-ecr-registry-deploy
        params:
          image: adot-ecr-registry-staging/image.tar
          additional_tags: adot-ecr-registry-staging/tag
        get_params:
          skip_download: true

  - name: copy-prometheus-pushgateway
    plan:
      - get: prometheus-pushgateway
        trigger: true
        params:
          format: oci
      - put: ecr-prometheus-pushgateway
        params:
          image: prometheus-pushgateway/image.tar
        get_params:
          skip_download: true
    on_failure:
      put: slack-notification
      attempts: 10
      params:
        channel: "#govuk-pay-starling"
        silent: true
        text: ":red-circle: Failed copying pushgateway:v1.6.0 image from Docker Hub to ECR - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse build #$BUILD_NAME>"
        icon_emoji: ":concourse:"
        username: pay-concourse
    on_success:
      put: slack-notification
      attempts: 10
      params:
        channel: "#govuk-pay-activity"
        silent: true
        text: ":green-circle: Copied pushgateway:v1.6.0 image from Docker Hub to ECR - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse build #$BUILD_NAME>"
        icon_emoji: ":concourse:"
        username: pay-concourse