---
resource_types:
  - name: concourse-pipeline
    type: docker-image
    source:
      repository: concourse/concourse-pipeline-resource

resources:
  - name: omnibus
    type: git
    source:
      uri: https://github.com/alphagov/pay-omnibus
      branch: develop

  - name: pay-pipelines
    type: concourse-pipeline
    source:
      target: ((concourse-url))
      teams:
        - name: ((concourse-team))
          username: ((concourse-username))
          password: ((concourse-password))

jobs:
  - name: update-pipelines
    plan:
      - get: omnibus
        trigger: true
      - put: pay-pipelines
        params:
          pipelines:
            - name: provision-envs
              team: ((concourse-team))
              config_file: omnibus/ci/pipelines/provision-envs.yml
            - name: dev-env-anshul
              team: ((concourse-team))
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-anshul
            - name: dev-env-richard
              team: ((concourse-team))
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-richard
            - name: dev-env-dan
              team: ((concourse-team))
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-dan
            - name: dev-env-dom
              team: ((concourse-team))
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-dom
            - name: dev-env-nim
              team: ((concourse-team))
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-nim
            - name: dev-env-oswald
              team: ((concourse-team))
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-oswald
            - name: dev-env-stephen
              team: ((concourse-team))
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-stephen
            - name: staging
              team: ((concourse-team))
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: staging
