resources:
  - name: toolbox-staging-deploy-config
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master 
      paths:
        - ci/pipelines/toolbox-staging-deploy.yml
  - name: pay-ci
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-ci
      branch: master
  - name: toolbox-ecr-registry-prod
    type: registry-image-resource-1-1-0
    icon: docker
    source:
      repository: govukpay/toolbox
      aws_access_key_id: ((readonly_access_key_id))
      aws_secret_access_key: ((readonly_secret_access_key))
      aws_session_token: ((readonly_session_token))
      aws_role_arn: arn:aws:iam::((pay_aws_prod_account_id)):role/concourse
      aws_ecr_registry_id: "((pay_aws_prod_account_id))"
      aws_region: eu-west-1
  - name: toolbox-ecr-registry-staging
    type: registry-image-resource-1-1-0
    icon: docker
    source:
      repository: govukpay/toolbox
      aws_access_key_id: ((readonly_access_key_id))
      aws_secret_access_key: ((readonly_secret_access_key))
      aws_session_token: ((readonly_session_token))
      aws_role_arn: arn:aws:iam::((pay_aws_staging_account_id)):role/concourse
      aws_ecr_registry_id: "((pay_aws_staging_account_id))"
      aws_region: eu-west-1
      variant: release

resource_types:
  - name: registry-image-resource-1-1-0
    type: registry-image
    source:
      repository: concourse/registry-image-resource
      tag: "1.1.0"

jobs:
  - name: update-toolbox-staging-ecr-pipeline
    plan:
      - get: toolbox-staging-deploy-config
        trigger: true
      - set_pipeline: toolbox-staging-deploy-config
        file: toolbox-staging-deploy-config/ci/pipelines/toolbox-staging-deploy.yml
  - name: toolbox-staging-deploy
    plan:
      - get: toolbox-staging-deploy-config
      - get: toolbox-ecr-registry-staging
        trigger: true
        params:
          format: oci
      - get: pay-ci
      - task: assume-role
        file: pay-ci/ci/tasks/assume-role.yml
        params:
          AWS_ROLE_ARN: arn:aws:iam::((pay_aws_staging_account_id)):role/concourse
          AWS_ROLE_SESSION_NAME: terraform-staging-assume-role
      - load_var: role
        file: assume-role/assume-role.json
        format: json
      - load_var: digest
        file: toolbox-ecr-registry-staging/digest
      - task: pull-tags-from-ecr-registry-staging
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: amazon/aws-cli
          params:
            AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
            AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
            AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
            AWS_REGION: eu-west-1
            AWS_REGISTRY_ID: "((pay_aws_staging_account_id))"
            DIGEST: ((.:digest))
            AWS_DEFAULT_OUTPUT: text
          inputs:
            - name: toolbox-ecr-registry-staging
          outputs:
            - name: docker_tags
          run:
            # N.B. We perform this (somewhat convoluted) step so that Big Concourse can correctly
            # assume a role when trying to list images from ECR.
            path: /bin/sh
            args:
            - -ec
            - |
              aws ecr list-images \
              --registry-id $AWS_REGISTRY_ID \
              --repository-name govukpay/toolbox \
              --query "imageIds[?imageDigest=='$DIGEST'][imageTag]" \
              | tr '\n' ' ' > docker_tags/tags.txt
      - task: deploy-to-staging
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: govukpay/concourse-runner
          run:
            path: /bin/bash
            args:
            - -ec
            - |
              echo "Imagine we just deployed to staging."
      - task: smoke-test-on-staging
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: govukpay/concourse-runner
          run:
            path: /bin/bash
            args:
            - -ec
            - |
              echo "Imagine we just smoked on staging."
      - task: set-ready-for-production-tags
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: govukpay/concourse-runner
          inputs:
          - name: docker_tags
          outputs:
          - name: docker_tags
          run:
            path: /bin/bash
            args:
            - -ec
            - |
              sed -i'' 's/ready-staging/ready-production/g' docker_tags/tags.txt
      - put: toolbox-ecr-registry-prod
        params:
          image: toolbox-ecr-registry-staging/image.tar
          additional_tags: docker_tags/tags.txt
      