---
version: 2
updates:
- package-ecosystem: docker
  directory: "/ci/docker/node-runner"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
    - dependencies
    - govuk-pay
- package-ecosystem: docker
  directory: "/ci/docker/concourse-runner"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
    - dependencies
    - govuk-pay
  ignore:
    - dependency-name: docker
      versions:
        - "> 20.10.16"
- package-ecosystem: docker
  directory: "/ci/docker/concourse-runner-with-java-17"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
    - dependencies
    - govuk-pay
  ignore:
    - dependency-name: docker
      versions:
        - "> 20.10.16"
