---
version: 2
updates:
- package-ecosystem: docker
  directory: "/ci/docker/node-runner"
  schedule:
    interval: daily
    time: "03:00"
  ignore:
    - dependency-name: "node"
      versions:
        - ">= 19"
  open-pull-requests-limit: 10
  labels:
    - dependencies
    - govuk-pay
    - docker
- package-ecosystem: docker
  directory: "/ci/docker/concourse-runner"
  schedule:
    interval: daily
    time: "03:00"
  ignore:
    - dependency-name: "docker"
      update-types: ["version-update:semver-major"]
  open-pull-requests-limit: 10
  labels:
    - dependencies
    - govuk-pay
    - docker
- package-ecosystem: docker
  directory: "/ci/docker/concourse-runner-with-java-17"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
    - dependencies
    - govuk-pay
    - docker
- package-ecosystem: docker
  directory: "/ci/docker/concourse-runner-with-java-21"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
    - dependencies
    - govuk-pay
    - docker
- package-ecosystem: docker
  directory: "/ci/docker/pact-broker"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
    - dependencies
    - govuk-pay
    - docker
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 0
  labels:
    - dependencies
    - govuk-pay
    - github_actions
