repos:
  - repo: local
    hooks:
      - id: validate-pipelines
        name: Validate Concourse pipelines
        entry: fly validate-pipeline -c
        files: ci/pipelines/.+\.(yml|yaml)$
        language: system
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [ '--baseline', '.secrets.baseline' ]
        exclude: ^package-lock.json
