FROM node:18.18.0-alpine3.18@sha256:28630a8b97ae8336d77b6dae5705bea816bdc1d6383901bb4495c521929a4091

# As of node 15 the docker container fails to npm install without either a WORKDIR or -g
WORKDIR /node-runner

RUN npm install -g aws-sdk@^2.x.x
RUN npm install -g aws4@^1.x.x
RUN npm install -g @octokit/rest@^18.x.x

ENV NODE_PATH=/usr/local/lib/node_modules
