platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine
    tag: latest
inputs:
  - name: ad-hoc-sql-scripts
  - name: pay-ci
run:
  path: ash
  args:
    - pay-ci/ci/scripts/ad-hoc-sql.sh
