platform: linux
image_resource:
  type: registry-image
  source:
    repository: ubuntu
    tag: 22.04
inputs:
  - name: ad-hoc-sql-scripts
  - name: pay-ci
run:
  path: /bin/bash
  args:
    - pay-ci/ci/scripts/ad-hoc-sql.sh
