container_limits: {}
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner-with-java-21
caches:
  - path: src/.m2
inputs:
  - name: ci
outputs:
  - name: build
params:
  app_name:
platform: linux
run:
  path: "/bin/ash"
  args: ['ci/ci/scripts/build-java-lambdas.sh']
