container_limits: {}
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner-with-java-21
caches:
  - path: src/.m2
inputs:
  - name: src
outputs:
  - name: build
params:
  app_name:
platform: linux
run:
  path: ash
  args:
  - -ec
  - |
    set -o pipefail
    
    cd src
    
    git fetch origin main:main
    git diff --name-only --diff-filter=d main~ main | xargs -n 1 dirname | grep '^bin-ranges-' | cut -f 1 -d "/" |  uniq > submodules.txt
    echo "Submodules to build:"
    cat submodules.txt

    export MAVEN_HOME=/usr/lib/mvn
    export PATH=$MAVEN_HOME/bin:$PATH
    export MAVEN_REPO="$PWD/.m2"

    cat <<'EOF' >settings.xml
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <localRepository>${env.MAVEN_REPO}</localRepository>
    </settings>
    EOF

    PACKAGE_VERSION="1.0.$(date +"%Y%m%d%H%M%S")"
    echo "PACKAGE_VERSION=$PACKAGE_VERSION"
    mvn versions:set -DnewVersion="$PACKAGE_VERSION"
    
    while read line; do
      mvn --global-settings settings.xml clean install --projects $line --also-make
    done < submodules.txt
    
    while read line; do
      mkdir ../build/$line
      cp $line/target/$line-*.jar ../build/$line
    done < submodules.txt
    
    cd ..
    
    ls -al build/bin-ranges-diff
    ls -al build/bin-ranges-integrity
    ls -al build/bin-ranges-promotion
    ls -al build/bin-ranges-transfer
