container_limits: {}
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner
caches:
  - path: src/.m2
inputs:
  - name: pay-ci
  - name: src
outputs:
  - name: build
params:
  app_name:
platform: linux
run:
  path: "/bin/ash"
  args: ['pay-ci/ci/scripts/build-java-lambdas.sh']
