---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: pactfoundation/pact-cli
params:
  PACT_BROKER_USERNAME: ((pact-broker-username))
  PACT_BROKER_PASSWORD: ((pact-broker-password))
  GIT_SHA: ((.:git-sha))
  APP_NAME:
  PACT_TAG:
run:
  path: /bin/sh
  args:
    - -ec
    - |
      pact-broker can-i-deploy \
        --broker-base-url https://pact-broker.deploy.payments.service.gov.uk/ \
        --pacticipant ${APP_NAME} \
        --version ${GIT_SHA} \
        --to ${PACT_TAG} \
        --broker-username ${PACT_BROKER_USERNAME} \
        --broker-password ${PACT_BROKER_PASSWORD}
