---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: govukpay/node-aws-sdk-runner
inputs:
  - name: pay-ci
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:
  AWS_REGION: "eu-west-1"
  CLUSTER_NAME:
  APP_NAME:
  APPLICATION_IMAGE_TAG:
  TELEGRAF_IMAGE_TAG:
  NGINX_IMAGE_TAG:
  NGINX_FORWARD_PROXY_IMAGE_TAG:
  CARBON_RELAY_IMAGE_TAG:
run:
  path: node
  args:
    - pay-ci/ci/scripts/check-release-versions.js