platform: linux
image_resource:
   type: registry-image
   source:
    repository: governmentdigitalservice/pay-concourse-runner
inputs:
  - name: pay-ci
params:
  REGIONS: eu-west-1
run:
  path: /bin/sh
  args: ['pay-ci/ci/scripts/check-sns-topic-unsubscribers.sh']
