platform: linux
image_resource:
   type: registry-image
   source:
    repository: governmentdigitalservice/pay-concourse-runner
params:
  REGIONS: eu-west-1
run:
  path: bash
  args: ['pay-ci/ci/scripts/check-sns-subscriptions.sh']
