---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: golang
    tag: 1.20-alpine
inputs:
  - name: src
run:
  path: sh
  dir: src
  args: ["../pay-ci/ci/scripts/check-pipelines-and-tasks.sh"]
