platform: linux
image_resource:
   type: registry-image
   source:
    repository: governmentdigitalservice/pay-concourse-runner
params:
  REGIONS: eu-west-1
run:
  path: /bin/bash
  args:
    - -c
    - |
      set -euo pipefail

      any_failed=0

      for REGION in $REGIONS; do
        TOPIC_ARNS=$(aws sns --region "$REGION" list-topics --query "Topics[].TopicArn" | jq -r '.[]')

        if [[ -z "$TOPIC_ARNS" ]]; then
          echo "No SNS topics found in $REGION"
          exit 1
        fi

        for TOPIC_ARN in $TOPIC_ARNS; do
          echo "Checking topic: $TOPIC_ARN in $REGION"

          subscription_arn=$(aws sns --region "$REGION" list-subscriptions-by-topic --topic-arn "$TOPIC_ARN" --query 'Subscriptions[].SubscriptionArn' --output text)
          if [ "$subscription_arn" == "Deleted" ] || [ "$subscription_arn" == "PendingConfirmation" ]; then
            echo "Topic subscription: $subscription_arn in region $REGION is unsubscribed."
            echo
            echo "If you can find the Zendesk email to resubscribe, do that; or"
            echo "If you can’t find it or it doesn’t work, talk to Starling"

            any_failed=$((any_failed+=1))
          fi
        done
      done

      if [ "$any_failed" -ne 0 ]; then
        echo "Some topics are unsubscribed from their email destinations. See above output"
        exit 1
      fi

