platform: linux
image_resource:
   type: registry-image
   source:
    repository: governmentdigitalservice/pay-node-runner
    tag: node16
inputs:
  - name: pay-ci
  - name: pay-infra
params:
  REGIONS:
run:
  path: node
  args: ['pay-ci/ci/scripts/check-sns-subscriptions.js']
