---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner
params:
  GITHUB_TOKEN:
  CONCOURSE_TEAM:
  FLY_PASSWORD:
inputs:
  - name: pay-ci
  - name: pkl-pipeline-pr
outputs:
  - name: diffs
run:
  path: ash
  args: ['pay-ci/ci/scripts/comment-on-pr-with-pkl-pipeline-diffs.sh']
