---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
params:
  APP_NAME:
  ACTION_NAME:
  ENV:
  APPLICATION_IMAGE_TAG:
  TELEGRAF_IMAGE_TAG:
  NGINX_IMAGE_TAG:
  NGINX_FORWARD_PROXY_IMAGE_TAG:
outputs:
  - name: snippet
run:
  path: sh
  args:
    - -c
    - |
      cat <<EOT >> snippet/success
      THIS MESSAGE RELATES TO FARGATE - IGNORE UNLESS WORKING ON MIGRATION
      :green-circle: ${ACTION_NAME} of ${APP_NAME} on ${ENV} was successful :tada:

      Version details:
      EOT

      cat <<EOT >> snippet/failure
      THIS MESSAGE RELATES TO FARGATE - IGNORE UNLESS WORKING ON MIGRATION
      :red_circle: ${ACTION_NAME} of ${APP_NAME} on ${ENV} failed

      Version details:
      EOT

      APP_RELEASE_NUMBER=$(echo ${APPLICATION_IMAGE_TAG} | sed 's/-release//')
      echo "${APP_NAME}: https://github.com/alphagov/pay-${APP_NAME}/releases/tag/alpha_release-${APP_RELEASE_NUMBER}" | \
      tee -a snippet/* || true

      [ -n "${NGINX_IMAGE_TAG}" ] && \
      NGINX_RELEASE_NUMBER=$(echo ${NGINX_IMAGE_TAG} | sed 's/-release//') &&\
      echo "nginx proxy: https://github.com/alphagov/pay-nginx-proxy/releases/tag/alpha_release-${NGINX_RELEASE_NUMBER}" | \
      tee -a snippet/* ||  true


      [ -n "${TELEGRAF_IMAGE_TAG}" ] && \
      echo "telegraf: https://github.com/alphagov/pay-telegraf/releases/tag/${TELEGRAF_IMAGE_TAG}" | \
      tee -a snippet/* || true

      [ -n "${NGINX_FORWARD_PROXY_IMAGE_TAG}" ] && \
      echo "nginx forward proxy: https://github.com/alphagov/pay-nginx-forward-proxy/releases/tag/${NGINX_FORWARD_PROXY_IMAGE_TAG}" | \
      tee -a snippet/* || true


