---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: 3
params:
  APP_NAME:
  ACTION_NAME:
  APPLICATION_IMAGE_TAG:
  ENV:
outputs:
  - name: snippet
run:
  path: ash
  args:
    - -c
    - |
      APP_RELEASE_NUMBER=$(echo "${APPLICATION_IMAGE_TAG}" | cut -f 1 -d '-')

      echo -n "${APP_NAME}" | tee -a snippet/app_name
      echo -n "${APP_RELEASE_NUMBER}" | tee -a snippet/app_release_number
      
      cat <<EOT >> snippet/start
      :rocket: ${ACTION_NAME} of <https://github.com/alphagov/pay-dockerfiles/releases/tag/${APPLICATION_IMAGE_TAG}|${APP_NAME} v${APPLICATION_IMAGE_TAG}> on ${ENV} is beginning
      EOT

      cat <<EOT >> snippet/success
      :green-circle: ${ACTION_NAME} of <https://github.com/alphagov/pay-dockerfiles/releases/tag/${APPLICATION_IMAGE_TAG}|${APP_NAME} v${APPLICATION_IMAGE_TAG}> on ${ENV} was successful :tada:
      EOT

      cat <<EOT >> snippet/failure
      :red_circle: ${ACTION_NAME} of <https://github.com/alphagov/pay-dockerfiles/releases/tag/${APPLICATION_IMAGE_TAG}|${APP_NAME} v${APPLICATION_IMAGE_TAG}> on ${ENV} failed. Version details:
      EOT
