---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
params:
  APP_NAME:
  ACTION_NAME:
  ENV:
  APPLICATION_IMAGE_TAG:
  TELEGRAF_IMAGE_TAG:
  NGINX_IMAGE_TAG:
  NGINX_FORWARD_PROXY_IMAGE_TAG:
outputs:
  - name: snippet
run:
  path: sh
  args:
    - -c
    - |
      APP_RELEASE_NUMBER=$(echo ${APPLICATION_IMAGE_TAG} | sed 's/-release//')

      cat <<EOT >> snippet/start
      :rocket: FARGATE ${ACTION_NAME} of <https://github.com/alphagov/pay-${APP_NAME}/releases/tag/alpha_release-${APP_RELEASE_NUMBER}|${APP_NAME} ${APP_RELEASE_NUMBER}-release> is beginning
      EOT

      cat <<EOT >> snippet/success
      :green-circle: FARGATE ${ACTION_NAME} of <https://github.com/alphagov/pay-${APP_NAME}/releases/tag/alpha_release-${APP_RELEASE_NUMBER}|${APP_NAME} v${APPLICATION_IMAGE_TAG}> on ${ENV} was successful :tada:
      EOT

      cat <<EOT >> snippet/failure
      :red_circle: FARGATE ${ACTION_NAME} of <https://github.com/alphagov/pay-${APP_NAME}/releases/tag/alpha_release-${APP_RELEASE_NUMBER}|${APP_NAME} v${APPLICATION_IMAGE_TAG}> on ${ENV} failed. Version details:
      EOT

      [ -n "${NGINX_IMAGE_TAG}" ] && \
      NGINX_RELEASE_NUMBER=$(echo ${NGINX_IMAGE_TAG} | sed 's/-release//') && \
      echo "- <https://github.com/alphagov/pay-nginx-proxy/releases/tag/alpha_release-${NGINX_RELEASE_NUMBER}|nginx-proxy v${NGINX_IMAGE_TAG}>" | \
      tee -a snippet/failure || true

      [ -n "${TELEGRAF_IMAGE_TAG}" ] && \
      echo "- <https://github.com/alphagov/pay-telegraf/releases/tag/${TELEGRAF_IMAGE_TAG}|telegraf v${TELEGRAF_IMAGE_TAG}>" | \
      tee -a snippet/failure || true

      [ -n "${NGINX_FORWARD_PROXY_IMAGE_TAG}" ] && \
      echo "- <https://github.com/alphagov/pay-nginx-forward-proxy/releases/tag/${NGINX_FORWARD_PROXY_IMAGE_TAG}|nginx-forward-proxy v${NGINX_FORWARD_PROXY_IMAGE_TAG}>" | \
      tee -a snippet/failure || true
