---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
params:
  CARBON_RELAY_IMAGE_TAG:
  ENV:
outputs:
  - name: snippet
run:
  path: sh
  args:
    - -c
    - |
      cat <<EOT >> snippet/success
      :green-circle: FARGATE Deployment of <https://github.com/alphagov/pay-dockerfiles/releases/tag/${CARBON_RELAY_IMAGE_TAG}|carbon-relay v${CARBON_RELAY_IMAGE_TAG}> on ${ENV} was successful :tada:
      EOT

      cat <<EOT >> snippet/failure
      :red_circle: FARGATE Deployment of <https://github.com/alphagov/pay-dockerfiles/releases/tag/${CARBON_RELAY_IMAGE_TAG}|carbon-relay v${CARBON_RELAY_IMAGE_TAG}> on ${ENV} failed. Version details:
      EOT
