---
platform: linux
inputs:
  - name: pay-infra
image_resource:
  type: registry-image
  source:
    repository: hashicorp/terraform
    tag: 1.3.7
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:
  AWS_REGION: eu-west-1
  APPLICATION_IMAGE_TAG:
  NGINX_IMAGE_TAG:
  NGINX_FORWARD_PROXY_IMAGE_TAG:
  APP_NAME:
  ACCOUNT:
  ENVIRONMENT:
run:
  path: /bin/sh
  args:
    - -ec
    - |
      cd pay-infra/provisioning/terraform/deployments/${ACCOUNT}/${ENVIRONMENT}/microservices_v2/${APP_NAME}
      terraform init
      terraform apply \
        -var application_image_tag=${APPLICATION_IMAGE_TAG} \
        -var forward_proxy_image_tag=${NGINX_FORWARD_PROXY_IMAGE_TAG} \
        -var nginx_image_tag=${NGINX_IMAGE_TAG} \
        -auto-approve
