---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-node-runner
    tag: node16
params:
  APP_NAME:
  APPLICATION_IMAGE_TAG: #eg 1339-release
inputs:
  - name: pay-ci
outputs:
  - name: git-sha
run:
  path: node
  args: ['pay-ci/ci/scripts/get-git-sha-for-release-tag.js']