platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: 3
inputs:
  - name: pay-ci
  - name: src
outputs:
  - name: tags
params:
  DOCKERFILE: "Dockerfile"
run:
  path: sh
  args: ['pay-ci/ci/scripts/get-image-tag-from-dockerfile.sh']
