platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest
inputs:
  - name: pay-ci
  - name: src
params:
  DOCKERFILE: "src/Dockerfile"
run:
  path: sh
  args: ['pay-ci/ci/scripts/get-image-tag-from-dockerfile.sh']
