---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner
params:
  GITHUB_TOKEN:
outputs:
  - name: sbom-data
run:
  path: sh
  args:
    - -ec
    - |
      apk add --no-progress --no-cache git github-cli

      mkdir -p sbom-data/

      DATE=$(date -I)
      OWNER="alphagov"

      set -- $(printf '%s\n' $(gh search repos --archived=false --owner="alphagov" --topic="govuk-pay" --limit=99 --json=name --jq ".[] | .name"))

      for repo do
          file=${DATE}_sbom_"${repo}".json
          curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB__TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${OWNER}/"${repo}"/dependency-graph/sbom \
              --output "${file}"
      done

      aws s3 sync sbom-data/ s3://govuk-pay-sbom-dev/${DATE}_github_sbom
