---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner
params:
  GITHUB_TOKEN:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:
  AWS_REGION: eu-west-1
run:
  path: /bin/sh
  args: ["pay-ci/ci/scripts/github-export-sbom.sh"]
