container_limits: {}
platform: linux
image_resource:
  type: registry-image
  source:
    repository: govukpay/concourse-runner
inputs:
  - name: src
outputs:
  - name: pacts
run:
  path: bash
  dir: src
  args:
    - -ec
    - |
      source /docker-helpers.sh
      start_docker

      function cleanup {
        echo "CLEANUP TRIGGERED"
        clean_docker
        stop_docker
        echo "CLEANUP COMPLETE"
      }

      trap cleanup EXIT

      commit="$(cat .git/resource/head_sha)"
      pr="$(cat .git/resource/pr)"
      mvn clean package \
                -DPACT_BROKER_URL=https://pact-broker-test.cloudapps.digital \
                -DPACT_BROKER_USERNAME="" \
                -DPACT_BROKER_PASSWORD="" \
                -DPACT_CONSUMER_VERSION="${commit}" \
                -DPACT_CONSUMER_TAG="${pr}" \
                -Dpact.provider.version="${commit}" \
                -DrunConsumerContractTests=true
      cp -R target/pacts/* ../pacts/ || true