container_limits: {}
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner
    tag: latest
caches:
  - path: src/.m2
inputs:
  - name: src
platform: linux
outputs:
  - name: pacts
run:
  path: bash
  args:
  - -ec
  - |
    source /docker-helpers.sh
    start_docker

    function cleanup {
      echo "CLEANUP TRIGGERED"
      clean_docker
      stop_docker
      echo "CLEANUP COMPLETE"
    }

    trap cleanup EXIT

    cd src

    export MAVEN_HOME=/usr/lib/mvn
    export PATH=$MAVEN_HOME/bin:$PATH
    export MAVEN_REPO="$PWD/.m2"

    cat <<'EOF' >settings.xml
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <localRepository>${env.MAVEN_REPO}</localRepository>
    </settings>
    EOF

    mvn --global-settings settings.xml clean verify

    cp -R target/pacts/* ../pacts/ || true
