---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner
    tag: latest

params:
  SOURCE_MANIFEST:
  NEW_MANIFEST:
  DOCKER_LOGIN_ECR: 0
  AWS_ACCOUNT_ID: 
  DOCKER_CONFIG: docker_creds

inputs:
  - name: docker_creds

run:
  path: bash
  args:
  - -ec
  - |
    if [ "$DOCKER_LOGIN_ECR" -eq 1 ]; then
      aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com"
    fi

    docker buildx imagetools create -t "$NEW_MANIFEST" "$SOURCE_MANIFEST"
