---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: pactfoundation/pact-cli
params:
  PACT_BROKER_USERNAME: ((pact-broker-username))
  PACT_BROKER_PASSWORD: ((jenkins-pact-broker-password))
  GIT_SHA:
  APP_NAME:
  PACT_TAG:
run:
  path: /bin/sh
  args:
    - -ec
    - |
      pact-broker create-version-tag \
        -b https://pact-broker-test.cloudapps.digital \
        -a ${APP_NAME} \
        -e ${GIT_SHA} \
        -t ${PACT_TAG} \
        -u ${PACT_BROKER_USERNAME} \
        -p ${PACT_BROKER_PASSWORD}
