# This task parses the candidate tag from an ecr resource and turns it into a *-perf release tag
#
# File written:
#   parse-perf-release-tag/tag : The perf release tag (e.g. 123-perf)
#
platform: linux
image_resource:
  type: registry-image
  source:
    repository: govukpay/node-runner
params:
  #e.g. "adminusers-db-migration-prod"
  BUILD_JOB_NAME:
inputs:
  - name: pay-ci
  - name: ecr-repo
outputs:
  - name: parse-perf-release-tag
run:
  path: node
  args: ['pay-ci/ci/scripts/parse-perf-release-tag.js']