platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine
inputs:
  - name: git-release
outputs:
  - name: tags
run:
  path: sh
  args:
    - -ec
    - |
      apk add --quiet --no-progress git

      RELEASE_NUMBER=$(cut -f 2 -d "-" < git-release/.git/ref)
      echo "${RELEASE_NUMBER}-release" | tee tags/tags
      echo "${RELEASE_NUMBER}-candidate" | tee tags/candidate-tag
      echo "${RELEASE_NUMBER}" > tags/release-number

      cd git-release
      git rev-parse HEAD | tee ../tags/release-sha
