# This task parses the candidate tag from an ecr resource and turns it into the final release tag
#
# Files written:
#   parse-candidate-tag/release-tag : The actual release tag (e.g. 123-release)
#   parse-candidate-tag/release-number : The number of the candidate release (e.g. in the case of 123-candidate, this is 123)
#
platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine
    tag: 3.16
inputs:
  - name: ecr-repo
outputs:
  - name: parse-candidate-tag
run:
  path: ash
  args:
    - -ec
    - |
      RELEASE_NUMBER=$(cut -f 1 -d "-" < ecr-repo/tag)
      echo "${RELEASE_NUMBER}-release" | tee parse-candidate-tag/release-tag
      echo "$RELEASE_NUMBER" > parse-candidate-tag/release-number

      # ecr-repo/respository looks like '223851549868.dkr.ecr.eu-west-1.amazonaws.com/govukpay/adminusers'
      # in awk FS is the field separator and NF is the number of fields, meaning we separate on / and print the last field
      APP_NAME=$(awk 'BEGIN { FS="/" } { print $NF }' < ecr-repo/repository)
      echo -n "APP name: "
      echo "${APP_NAME}" | tee parse-candidate-tag/app_name
      echo
