platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine
inputs:
  - name: git-release
outputs:
  - name: tags
run:
  path: sh
  args:
    - -ec
    - |
      RELEASE_NUMBER=$(sed 's/alpha_release-//' < git-release/.git/ref)
      echo "${RELEASE_NUMBER}-release" > tags/tags
      echo "${RELEASE_NUMBER}-candidate" > tags/candidate-tag
