platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine
    tag: 3
inputs:
  - name: git-release
outputs:
  - name: tags
params:
  APP_NAME:
run:
  path: ash
  args:
    - -ec
    - |
      apk add --quiet --no-progress git

      RELEASE_NUMBER=$(cut -f 2 -d "-" < git-release/.git/ref)
      echo "${RELEASE_NUMBER}-release" | tee tags/tags
      echo "${RELEASE_NUMBER}-candidate" | tee tags/candidate-tag
      echo "${RELEASE_NUMBER}" > tags/release-number
      date +%Y-%m-%d_%H-%M-%S | tee tags/date
      echo -n "${RELEASE_NUMBER}-release " >> tags/all-release-tags
      cat tags/date >> tags/all-release-tags
      echo -n "${RELEASE_NUMBER}-candidate " >> tags/all-candidate-tags
      cat tags/date >> tags/all-candidate-tags

      if [ -z "${APP_NAME:-}" ]; then
        # in awk FS is the field separator and NF is the number of fields, meaning we separate on / and print the last field
        APP_NAME=$(grep 'url = ' < git-release/.git/config | awk '{ print $3 }' | awk 'BEGIN { FS="/" } { print $NF }' | sed -E 's/^pay-//')
      fi
      echo -n "APP name: "
      echo "${APP_NAME}" | tee tags/app_name
      echo
      
      cd git-release
      git rev-parse HEAD | tee ../tags/release-sha
