---
# This task zips up the pay-ci repository (provided as the input pay-ci), uploads it to s3, and generates the json
# configurations (card.json, products.json) required by the run-codebuild tasks later. The configuration includes:
#
#   1. The codebuild project to execute
#   2. The source version of pay-ci on s3 (this is the version id of the s3 object that is uploaded)
#   3. Environment variables to say which set of endtoend tests to execute, and the project and version under test
#       (e.g. frontend 3-release)
#
# The json configuration is written into the run-codebuild-configuration output for a later task to use as an input
platform: linux
image_resource:
  type: registry-image
  source:
    repository: govukpay/concourse-runner
inputs:
  - name: pay-ci
outputs:
  - name: run-codebuild-configuration
params:
  CODEBUILD_PROJECT_NAME:
  CODEBUILD_SOURCES_BUCKET:
  PROJECT_UNDER_TEST:
  RELEASE_TAG_UNDER_TEST:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:
run:
  path: /bin/bash
  args:
    - -euo
    - pipefail
    - -c
    - |
      echo "Installing zip"
      apk add -q --no-progress zip
      echo "Done"
      echo

      pushd "pay-ci" >> /dev/null
      echo "Zipping pay-ci"
      zip -qr "../pay-ci.zip" .
      popd >> /dev/null

      echo "Uploading pay-ci.zip to S3"
      PAY_CI_VERSION_ID=$(
        aws s3api put-object \
          --bucket "${CODEBUILD_SOURCES_BUCKET}" \
          --key "sources/endtoend/pay-ci.zip" \
          --body "pay-ci.zip" \
          --query 'VersionId' \
          --output 'text'
      )
      echo "Uploaded pay-ci with version id $PAY_CI_VERSION_ID"
      echo
      echo "Products end to end test configuration"
      cat <<EOF | tee ./run-codebuild-configuration/products.json
      {
        "projectName": "${CODEBUILD_PROJECT_NAME}",
        "sourceVersion": "${PAY_CI_VERSION_ID}",
        "secondarySourcesVersions": {},
        "environmentVariables": {
          "tag_${PROJECT_UNDER_TEST}": "${RELEASE_TAG_UNDER_TEST}",
          "END_TO_END_TEST_SUITE": "products"
        }
      }
      EOF

      echo
      echo "Card end to end test configuration"
      cat <<EOF | tee ./run-codebuild-configuration/card.json
      {
        "projectName": "${CODEBUILD_PROJECT_NAME}",
        "sourceVersion": "${PAY_CI_VERSION_ID}",
        "secondarySourcesVersions": {},
        "environmentVariables": {
          "tag_${PROJECT_UNDER_TEST}": "${RELEASE_TAG_UNDER_TEST}",
          "END_TO_END_TEST_SUITE": "card"
        }
      }
      EOF
