---
# The JSON configuration is written into the run-codebuild-configuration 
# output for a later task to use as an input

platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner
inputs:
  - name: pay-ci
outputs:
  - name: run-codebuild-configuration
params:
  PROJECT_TO_BUILD:
  RELEASE_NAME:
  RELEASE_NUMBER:
  RELEASE_SHA:
  BUILD_DATE:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:
run:
  path: /bin/bash
  args:
    - -euo
    - pipefail
    - -c
    - |
      echo "Writing amd64 CodeBuild configuration"
      cat <<EOAMD | tee ./run-codebuild-configuration/${PROJECT_TO_BUILD}-amd64.json
      {
        "projectName": "pay-${PROJECT_TO_BUILD}-amd64",
        "sourceVersion": "${RELEASE_SHA}",
        "secondarySourcesVersions": {},
        "environmentVariables": {
          "RELEASE_NUMBER": "${RELEASE_NUMBER}",
          "RELEASE_NAME": "${RELEASE_NAME}",
          "RELEASE_SHA": "${RELEASE_SHA}",
          "BUILD_DATE": "${BUILD_DATE}"
        }
      }
      EOAMD

      echo "Writing armv8 CodeBuild configuration"
      cat <<EOF | tee ./run-codebuild-configuration/${PROJECT_TO_BUILD}-armv8.json
      {
        "projectName": "pay-${PROJECT_TO_BUILD}-armv8",
        "sourceVersion": "${RELEASE_SHA}",
        "secondarySourcesVersions": {},
        "environmentVariables": {
          "RELEASE_NUMBER": "${RELEASE_NUMBER}",
          "RELEASE_NAME": "${RELEASE_NAME}",
          "RELEASE_SHA": "${RELEASE_SHA}",
          "BUILD_DATE": "${BUILD_DATE}"
        }
      }
      EOF

      echo "Writing manifest CodeBuild configuration"
      cat <<EOF | tee ./run-codebuild-configuration/${PROJECT_TO_BUILD}-manifest.json
      {
        "projectName": "pay-${PROJECT_TO_BUILD}-armv8",
        "secondarySourcesVersions": {},
        "environmentVariables": {
          "RELEASE_NUMBER": "${RELEASE_NUMBER}",
          "BUILD_DATE": "${BUILD_DATE}"
        }
      }
      EOF
