---
# This task zips up the pay-perftests repository (provided as the input pay-perftests), uploads it to s3, and generates
# the json configuration required by the run-codebuild tasks later. The configuration includes:
#
#   1. The codebuild project to execute
#   2. The source version of pay-perftests on s3 (this is the version id of the s3 object that is uploaded)
#   3. Environment variables to say which perftest docker image to use (e.g. 3-release)
#
# The json configuration is written into the run-codebuild-configuration output for a later task to use as an input
platform: linux
image_resource:
  type: registry-image
  source:
    repository: govukpay/concourse-runner
inputs:
  - name: pay-perftests
outputs:
  - name: run-codebuild-configuration
params:
  PERF_TESTS_VERSION:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:
run:
  path: /bin/bash
  args:
    - -euo
    - pipefail
    - -c
    - |
      echo "Installing zip"
      apk add -q --no-progress zip
      echo "Done"
      echo

      pushd "pay-perftests" >> /dev/null
      echo "Zipping pay-perftests"
      zip -qr "../pay-perftests.zip" .
      popd >> /dev/null

      echo "Uploading pay-perftests.zip to S3"
      PAY_PERFTESTS_VERSION_ID=$(
        aws s3api put-object \
          --bucket "pay-govuk-codebuild-test-perf-1" \
          --key "sources/perf-tests/pay-perftests.zip" \
          --body "pay-perftests.zip" \
          --query 'VersionId' \
          --output 'text'
      )

      echo "Uploaded pay-perftests with version id $PAY_PERFTESTS_VERSION_ID"
      echo
      echo "Products end to end test configuration"
      cat <<EOF | tee ./run-codebuild-configuration/perf-tests.json
      {
        "projectName": "perf-tests-test-perf-1",
        "sourceVersion": "${PAY_PERFTESTS_VERSION_ID}",
        "secondarySourcesVersions": {},
        "environmentVariables": {
          "PERF_TESTS_VERSION": "${PERF_TESTS_VERSION}"
        }
      }
      EOF
