platform: linux
image_resource:
  type: registry-image
  source:
    repository: dwdraju/alpine-curl-jq
inputs:
  - name: src
  - name: pacts
params:
  consumer_name:
  broker_username: ((pact-broker-username))
  broker_password: ((pact-broker-password))
run:
  path: sh
  args:
    - -c
    - |

      if [ ! -f src/.git/resource/head_sha ]; then
        echo "ERROR: src/.git/resource/head_sha/ does not exist."
        exit 1
      fi

      version="$(cat src/.git/resource/head_sha)"
      pr="$(cat src/.git/resource/pr)"
      cd pacts || exit 1
      for pact in $(ls . | grep -v '\-to\-'); do
        provider_name=$(jq .provider.name < "$pact" | tr -d '"')
        curl -v --fail -X PUT -H "Content-Type: application/json" \
        -d@"$pact" \
        --user ${broker_username}:${broker_password} \
        https://pay-concourse-pact-broker.cloudapps.digital/pacts/provider/"${provider_name}"/consumer/"${consumer_name}"/version/"${version}"
        
        curl -v --fail -X PUT -H "Content-Type: application/json" \
        --user ${broker_username}:${broker_password} \
        https://pay-concourse-pact-broker.cloudapps.digital/pacticipants/"${consumer_name}"/versions/"${version}"/tags/"${pr}"
      done
