---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner

inputs:
  - name: pay-ci
  - name: pay-cli

params:
  ECR_REPO:
  IMAGE_TAG:
  AWS_DEFAULT_REGION: "eu-west-1"
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:
  PAY_CLI_PATH: "../../../../pay-cli"

run:
  path: /bin/sh
  args:
    - -eu
    - -c
    - |
      cd pay-ci/ci/scripts/test-bastion
      npm install
      node index.js
