---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-node-runner
    tag: node16
inputs:
  - name: pay-ci
outputs:
  - name: smoke-test-results
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:
  AWS_REGION:
  SMOKE_TEST_NAME:
run:
  path: node
  args: ['pay-ci/ci/scripts/run_smoke_test.js']
