---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine
    tag: 3.16
params:
  BUILD_PIPELINE_NAME:
  BUILD_JOB_NAME:
  RELEASE_NUMBER:
  HOSTED_GRAPHITE_API_TOKEN:
run:
  path: sh
  args:
    - -ec
    - |
      RELEASE=$(echo "${RELEASE_NUMBER}" | cut -d'-' -f 1)
      METRIC_DATA="${HOSTED_GRAPHITE_API_TOKEN}.ci.concourse.$BUILD_PIPELINE_NAME.$BUILD_JOB_NAME.releaseNumber $RELEASE"
      echo "$METRIC_DATA" | nc carbon.hostedgraphite.com 2003
