---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine
params:
  ENVIRONMENT:
  APP_NAME:
  RELEASE_NUMBER:
  HOSTED_GRAPHITE_API_TOKEN:
run:
  path: sh
  args:
    - -ec
    - |
      RELEASE=$(echo $RELEASE_NUMBER| cut -d'-' -f 1)
      METRIC_DATA="${HOSTED_GRAPHITE_API_TOKEN}.ci.concourse.release.${ENVIRONMENT}.${APP_NAME}.releaseNumber $RELEASE"
      echo $METRIC_DATA | nc carbon.hostedgraphite.com 2003
