---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: govukpay/concourse-runner
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:    
  AWS_REGION: eu-west-1
  ENVIRONMENT:
run:
  path: /bin/bash
  args:
    - -ec
    - |
      for canary in notifcatns_sndbx_$ENVIRONMENT pymntlnk_sandbox_$ENVIRONMENT cancel_sandbox_$ENVIRONMENT card_wpay_3ds2ex_$ENVIRONMENT \
      card_wpay_3ds2_$ENVIRONMENT card_wpay_3ds_$ENVIRONMENT card_wpay_$ENVIRONMENT card_stripe_3ds_$ENVIRONMENT card_stripe_$ENVIRONMENT card_sandbox_$ENVIRONMENT \
      s_card_stripe_$ENVIRONMENT s_card_stripe_3d_$ENVIRONMENT s_card_wpay_$ENVIRONMENT s_card_wpay_3ds_$ENVIRONMENT s_card_wpay_3ds2_$ENVIRONMENT \
      s_wpay_3ds2ex_$ENVIRONMENT s_card_sandbox_$ENVIRONMENT s_cancel_sandbox_$ENVIRONMENT s_paylnk_sandbox_$ENVIRONMENT s_notifications_$ENVIRONMENT; do

        status=$(aws --region "$AWS_REGION" synthetics get-canary --name $canary | jq -r '.Canary.Status.State')
        if [ "$status" == "RUNNING" ]
        then
          echo "Stopping canary $canary"
          aws --region "$AWS_REGION" synthetics stop-canary --name $canary
        elif [ "$status" == "ERROR" ]
        then  
          echo "Canary $canary is in an errored state. It must be manually deleted and created - see https://pay-team-manual.cloudapps.digital/manual/tools/canary.html#updating-canary-tests-in-error-state."
          exit 1
        else
          echo "Canary $canary is not running, nothing to do."
        fi
      done