---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: govukpay/concourse-runner  
params:
  RDS_INSTANCE_NAME:
  AWS_DEFAULT_REGION: eu-west-1
  MAX_ATTEMPTS: 100
run:
  path: /bin/bash
  args:
    - -euo
    - pipefail
    - -c
    - |
      echo "Stopping RDS instance ${RDS_INSTANCE_NAME}"
      aws rds stop-db-instance --db-instance-identifier "${RDS_INSTANCE_NAME}" >> /dev/null

      TOTAL_WAIT_TIME_IN_MINUTES=$((MAX_ATTEMPTS * 15 / 60))

      echo "Starting to wait up to ${TOTAL_WAIT_TIME_IN_MINUTES} minutes for RDS instance ${RDS_INSTANCE_NAME} to stop"

      function db_instance_state() {
        aws rds describe-db-instances --db-instance-identifier "${RDS_INSTANCE_NAME}" --query "DBInstances[0].DBInstanceStatus" --output text
      }

      for ATTEMPT in $(seq 1 "${MAX_ATTEMPTS}"); do
        CURRENT_STATE=$(db_instance_state)

        if [ "${CURRENT_STATE}" == "stopped" ]; then
          echo "The RDS instance ${RDS_INSTANCE_NAME} is now stopped"
          exit 0
        fi

        echo "The RDS instance ${RDS_INSTANCE_NAME} is currently in state ${CURRENT_STATE}." \
            "Waiting 15 seconds before checking again. Attempt ${ATTEMPT}/${MAX_ATTEMPTS}"
        sleep 15
      done

      echo "RDS instance ${RDS_INSTANCE_NAME} did not reach the stopped state within ${TOTAL_WAIT_TIME_IN_MINUTES} minutes"
      exit 1
