---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: govukpay/concourse-runner
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:    
  AWS_REGION: eu-west-1
run:
  path: /bin/bash
  args:
    - -ec
    - |
      for canary in card_wpay_3ds_test card_wpay_test card_stripe_3ds_test card_stripe_test; do

        status=$(aws --region "$AWS_REGION" synthetics get-canary --name $canary | jq -r '.Canary.Status.State')
        echo "status: $status"
        if [ "$status" == "RUNNING" ]
        then
          echo "Stopping canary $canary"
          aws --region "$AWS_REGION" synthetics stop-canary --name $canary
        elif [ "$status" == "ERROR" ]
        then  
          echo "Canary $canary is in an errored state. It must be manually deleted and created - see https://pay-team-manual.cloudapps.digital/manual/tools/canary.html#updating-canary-tests-in-error-state."
          exit 1
        else
          echo "Canary $canary is not running, nothing to do."
        fi
      done