---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: govukpay/concourse-runner
params:
  AWS_REGION: eu-west-1
run:
  path: /bin/bash
  args:
    - -ec
    - |
      for canary in card_wpay_3ds_test card_wpay_test card_stripe_3ds_test card_stripe_test; do

        status=$(aws --region $AWS_REGION synthetics get-canary --name $canary | jq -r '.Canary.Status.State')
        echo "status: $status"
        if [ "$status" == "RUNNING" ]
        then
          echo "Stopping canary $canary"
          aws --region $AWS_REGION synthetics stop-canary --name $canary
        else
          echo "Canary $canary is not running, nothing to do."
        fi
      done