---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner
inputs:
  - name: src
params:
  GH_ACCESS_TOKEN: ((github-access-token))
outputs:
  - name: src
run:
  path: ash
  dir: src
  args: ["pay-ci/ci/scripts/update-cardid-submodule.sh"]
