---
inputs:
  - name: pay-ci
platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-node-runner
    tag: node16
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:
  AWS_REGION: eu-west-1
  APP_NAME:
  APPLICATION_IMAGE_TAG:
  NGINX_IMAGE_TAG:
  ENVIRONMENT:
run:
  path: node
  args:
    - pay-ci/ci/scripts/wait-for-deploy.js
