platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner
inputs:
  - name: pay-ci
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:
  MAX_ATTEMPTS: 480 # 2 Hours to account for DBs backing up, configuring enhanced monitoring, etc
run:
  path: "/bin/ash"
  args: ['pay-ci/ci/scripts/perf-test-cleanup/check-for-running-db.sh']
