platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner
inputs:
  - name: pay-ci
  - name: run-cleanup-task
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:
run:
  path: "/bin/ash"
  args: ['pay-ci/ci/scripts/perf-test-cleanup/wait-for-task.sh']
