platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner
inputs:
  - name: pay-ci
  - name: lock-status
params:
  FLY_PASSWORD:
run:
  path: "/bin/ash"
  args: ['pay-ci/ci/scripts/lock-pools/detect-deadlock-from-failed-job.sh']
