---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner
run:
  path: /bin/ash
  args:
    - -c
    - |
      set -euo pipefail

      exit 1
