platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentdigitalservice/pay-concourse-runner
inputs:
  - name: lock-pool-repo
outputs:
  - name: lock-status
params:
  LOCK_NAME:
run:
  path: "/bin/ash"
  dir: "lock-pool-repo"
  args: ['pay-ci/ci/scripts/lock-pools/report-lock-status.sh']
