# This workflow creates an alpha_release-XXX tag on the repository it's called from at the head of master.
# The number to suffix is discovered by finding the previous highest and then incrementing by 1, or in the
# case that no release tag exists already by starting at 1.
#
# NOTE: This requires repository write permissions so you should pin to the master branch
#
# Usage:
#
# jobs:
#   create-release-tag:
#     uses: alphagov/pay-ci/.github/workflows/_run-node-unit-tests.yml@master
#
name: Create alpha_release tag

on:
  workflow_call:
    inputs:
      tag_prefix:
        description: An additional prefix to add the to the tag. This must not contain any hyphens!
        default: ""
        required: false
        type: string

permissions:
  contents: read

jobs:
  tag-release:
    needs: unit-tests
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - name: Git checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          fetch-depth: '0'
      - name: Tag release
        run: |
          LATEST_RELEASE_NUMBER=$(git describe --abbrev=0 --tags --match "${{ inputs.tag_prefix }}alpha_release-*" | awk -F- '{print $2}' || true)
          number_regex='^[0-9]+$'
          if ! [[ ${LATEST_RELEASE_NUMBER} =~ $number_regex ]]; then
           LATEST_RELEASE_NUMBER=0
          fi
          NEW_RELEASE_NUMBER=$((LATEST_RELEASE_NUMBER + 1))
          TAG_NAME=${{ inputs.tag_prefix }}alpha_release-${NEW_RELEASE_NUMBER}
          echo "TAG_NAME: ${TAG_NAME}"
          git config user.email payments-team@digital.cabinet-office.gov.uk
          git config user.name pay-github-actions
          DATE=$(date +%Y-%m-%d:%H:%M:%S)
          git tag -a ${TAG_NAME} ${GITHUB_SHA} -m "Release candidate tag created on ${DATE}"
          git push origin --tags

