# This workflow is meant to be run on a pact provider build. It will check pacts for
# all the consumers that depend on it against itself (the provider).
#
name: Provider Contract Tests

on:
  workflow_call:
    inputs:
      java_version:
        type: string
        required: false
        default: 21
        description: JDK version to setup and run tests. Defaults to 11
    secrets:
      pact_broker_username:
        required: true
      pact_broker_password:
        required: true

permissions:
  contents: read

jobs:
  provider-contract-tests:
    name: Contract tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Pull docker image dependencies
        run: |
          docker pull postgres:15.2
      - name: Set Pact Provider Version
        id: set-pact-provider-version
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # Github actually creates a phantom merge commit on PR actions, but we want to record
            # in the pact broker something we can actually trace back to a PR, using the _actual_
            # phantom merge commit sha (github.sha) would make this essentially impossible for us
            PROVIDER_VERSION=${{ github.event.pull_request.head.sha }}
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]] || [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            PROVIDER_VERSION=${{ github.sha }}
          else
            echo "Unknown type to get provider tag from, failing on purpose"
            exit 1
          fi
          echo "Setting Provider version to ${PROVIDER_VERSION}"
          echo "pact-provider-version=${PROVIDER_VERSION}" >> $GITHUB_OUTPUT
      - name: Run provider contract tests
        run: |
          mvn test --no-transfer-progress \
          -DrunContractTests \
          -DPACT_CONSUMER_TAG=master \
          -DPACT_BROKER_USERNAME=${{ secrets.pact_broker_username }} \
          -DPACT_BROKER_PASSWORD=${{ secrets.pact_broker_password }} \
          -Dpact.provider.version=${{ steps.set-pact-provider-version.outputs.pact-provider-version }} \
          -Dpact.verifier.publishResults=true
