name: Github Actions Tests

on:
  workflow_call:
    inputs:
      publish_pacts:
        type: boolean
        required: false
        default: false
        description: Set to `true` if app is a consumer and to publish pacts
      run_app_as_provider_contract_tests:
        type: boolean
        required: false
        default: false
        description: Set to `true` if app is a provider and run `App as provider` contract tests
      java_version:
        type: string
        required: false
        default: 11
      consumer_tag:
        type: string
        required: true
    secrets:
      pact_broker_username:
        required: false
        description: required if `publish_pacts` or `run_app_as_provider_contract_tests` is `true`
      pact_broker_password:
        required: false
        description: required if `publish_pacts` or `run_app_as_provider_contract_tests` is `true`

permissions:
  contents: read

jobs:
  integration-tests:
    name: Unit and Integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache pacts directory
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: target/pacts
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-pacts
      - name: Pull docker image dependencies
        run: |
          docker pull postgres:15.2
      - name: Compile
        run: mvn clean compile
      - name: Check for OpenApi file changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Changes to the OpenApi file have not been committed. Run \`mvn compile\` on your branch to regenerate the file and then commit the changes."
            exit 1
          fi
      - name: Run unit and integration tests
#        run: mvn verify
        run: mvn test
      - name: Check for generated pacts
        if: ${{ inputs.publish_pacts }}
        run: |
          if [ ! -d target/pacts ]; then
            echo "The pact files were not generated, this means that no pact results will be published and this build will fail to deploy"
            exit 1
          fi

  consumer-contract-tests:
    if: ${{ inputs.publish_pacts }}
    needs:
      - integration-tests
    runs-on: ubuntu-latest
    name: Publish consumer pacts
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Set up JDK 11
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache pacts directory
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: target/pacts
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-pacts
      - name: Publish consumer pacts
        run: |
          mvn pact:publish -DPACT_BROKER_URL=https://pact-broker.deploy.payments.service.gov.uk \
          -DrunConsumerContractTests \
          -DPACT_BROKER_USERNAME=${{ secrets.pact_broker_username }} \
          -DPACT_BROKER_PASSWORD=${{ secrets.pact_broker_password }} \
          -DPACT_CONSUMER_TAG="${{ inputs.consumer_tag }}" \
          -DPACT_CONSUMER_VERSION=${{ github.sha }}

  app-as-provider-contract-tests:
    name: 'App as provider'
    if: ${{ inputs.run_app_as_provider_contract_tests }}
    needs:
      - integration-tests
    uses: alphagov/pay-ci/.github/workflows/_run-app-as-provider-contract-tests.yml@pp_12590_reusable_workflows
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}
