name: Github Actions for NodeJS apps - run unit tests and publish pacts

on:
  workflow_call:
    inputs:
      publish_pacts:
        type: boolean
        required: false
        default: false
        description: Set to `true` if app is a consumer and to publish pacts
    secrets:
      pact_broker_username:
        required: false
        description: required if `publish_pacts` is `true`
      pact_broker_password:
        required: false
        description: required if `publish_pacts` is `true`

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: ".nvmrc"
      - name: Cache build directories
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: |
            node_modules
            govuk_modules
            public
            dist
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}
      - name: Cache pacts directory
        if: ${{ inputs.publish_pacts }}
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: pacts
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-pacts
      - name: Run unit tests
        run: npm test -- --forbid-only --forbid-pending

  publish-consumer-contracts:
    if: ${{ inputs.publish_pacts }}
    needs: unit-tests
    runs-on: ubuntu-latest
    name: Publish and tag consumer pacts
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: ".nvmrc"
      - name: Cache build directories
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: |
            node_modules
            govuk_modules
            public
            dist
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}
      - name: Cache pacts directory
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: pacts
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-pacts
      - name: Check for generated pacts
        run: |
          if [ ! -d pacts ]; then
            echo "The pact files were not generated, this means that no pact results will be published and this build will fail to deploy"
            exit 1
          fi
      - name: Set Pact Consumer variables
        id: set-pact-consumer-variables
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # Github actually creates a phantom merge commit on PR actions, but we want to record
            # in the pact broker something we can actually trace back to a PR, using the _actual_
            # phantom merge commit sha (github.sha) would make this essentially impossible for us
            CONSUMER_VERSION=${{ github.event.pull_request.head.sha }}
            CONSUMER_TAG=${{ github.event.pull_request.number }}
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]] || [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            CONSUMER_VERSION=${{ github.sha }}
            CONSUMER_TAG=master
          else
            echo "Unknown type to get consumer tag from, failing on purpose"
            exit 1
          fi
          echo "Setting Consumer version to ${CONSUMER_VERSION}"
          echo "pact-consumer-version=${CONSUMER_VERSION}" >> $GITHUB_OUTPUT
          echo "Setting Consumer tag to ${CONSUMER_TAG}"
          echo "pact-consumer-tag=${CONSUMER_TAG}" >> $GITHUB_OUTPUT
      - name: Publish and tag consumer pacts
        uses: pact-foundation/pact-broker-cli@0.7.1
        run: | 
          pact-broker-cli publish ./pacts \
          --consumer-app-version ${{ env.PACT_CONSUMER_VERSION }} \
          --broker-base-url ${{ env.PACT_BROKER_URL }} \
          --broker-username ${{ env.PACT_BROKER_USERNAME }} \
          --broker-password ${{ env.PACT_BROKER_PASSWORD }}
        env:
          PACT_BROKER_URL: https://pact-broker.deploy.payments.service.gov.uk
          PACT_BROKER_USERNAME: ${{ secrets.pact_broker_username }}
          PACT_BROKER_PASSWORD: ${{ secrets.pact_broker_password }}
          PACT_CONSUMER_TAG: ${{ steps.set-pact-consumer-variables.outputs.pact-consumer-tag }}
          PACT_CONSUMER_VERSION: ${{ steps.set-pact-consumer-variables.outputs.pact-consumer-version }}
          