name: Github Actions Tests

on:
  workflow_call:
    inputs:
      provider:
        type: string
        required: true
        description: Name of the provider. Example -  connector
      consumer:
        description: Name of the consumer app, e.g. frontend
        required: true
        type: string
      consumer_tag:
        description: Consumer tag. This could be branch name ('master'), PR number ('1234') or deploy tag ('test-fargate')
        required: true
        type: string
      java_version:
        type: string
        required: false
        default: 11
    secrets:
      pact_broker_username:
        required: true
      pact_broker_password:
        required: true

permissions:
  contents: read

jobs:
  contract-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          repository: alphagov/pay-${{ inputs.provider }}
          path: pay-${{ inputs.provider }}
      - name: Get Provider SHA
        id: get-provider-sha
        run: |
          cd pay-${{ inputs.provider }}
          echo "provider-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo $provider-sha
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Pull docker image dependencies
        run: |
          docker pull postgres:15.2
      - name: Run provider pact tests
        run: |
          export MAVEN_REPO="$HOME/.m2"
          cd pay-${{ inputs.provider }}

          mvn test \
          --batch-mode \
          -DrunContractTests \
          -DCONSUMER="${{ inputs.consumer }}" \
          -DPACT_CONSUMER_TAG="${{ inputs.consumer_tag }}" \
          -Dpact.provider.version="${{ steps.get-provider-sha.outputs.provider-sha }}" \
          -Dpact.verifier.publishResults=true \
          -DPACT_BROKER_HOST=pact-broker.deploy.payments.service.gov.uk \
          -DPACT_BROKER_USERNAME="${{ secrets.pact_broker_username }}" \
          -DPACT_BROKER_PASSWORD="${{ secrets.pact_broker_password }}"

