name: Detect secrets
on:
  pull_request:
  workflow_call:

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Detect secrets
        uses: alphagov/pay-ci/actions/detect-secrets@master
