name: Detect secrets
on:
  pull_request:
  workflow_call:

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Detect secrets
        uses: alphagov/pay-ci/actions/detect-secrets@master
