name: Detect secrets
on:
  pull_request:
  workflow_call:

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247
      - name: Detect secrets
        uses: alphagov/pay-ci/actions/detect-secrets@master
