name: Detect secrets
on:
  pull_request:
  workflow_call:

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - name: Detect secrets
        uses: alphagov/pay-ci/actions/detect-secrets@master
