name: Test run-codebuild ci script

on:
  pull_request:
    paths:
      - 'ci/scripts/run-codebuild/**'
      - '.github/workflows/test-run-codebuild.yml'
  push:
    branches:
      - master
    paths:
      - 'ci/scripts/run-codebuild/**'

jobs:
  test-script-run-codebuild:
    runs-on: ubuntu-20.04
    name: Test script run-codebuild
    env:
      working-directory: ci/scripts/run-codebuild

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 18.18.0
      - name: Install dependencies
        run: npm ci
        working-directory: 'ci/scripts/run-codebuild'
      - name: Lint check
        run: npm run lint
        working-directory: 'ci/scripts/run-codebuild'
      - name: Unit tests
        run: npm test
        working-directory: 'ci/scripts/run-codebuild'
