name: Run Semver Action Tests

on:
  pull_request:
    paths:
      - 'actions/next-semver/**'
      - '.github/workflows/test-semver.yml'
  push:
    branches:
      - master
    paths:
      - 'actions/next-semver/**'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247
      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: 'actions/next-semver/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'actions/next-semver/package-lock.json'
      - name: Install dependencies
        working-directory: 'actions/next-semver'
        run: npm ci
      - name: Run unit tests
        working-directory: 'actions/next-semver'
        run: npm run test
