name: Run Semver Action Tests

on:
  pull_request:
    paths:
      - 'actions/next-semver/**'
      - '.github/workflows/test-semver.yml'
  push:
    branches:
      - master
    paths:
      - 'actions/next-semver/**'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version-file: 'actions/next-semver/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'actions/next-semver/package-lock.json'
      - name: Install dependencies
        working-directory: 'actions/next-semver'
        run: npm ci
      - name: Run unit tests
        working-directory: 'actions/next-semver'
        run: npm run test
