name: Test run-codebuild ci script

on:
  pull_request:
    paths:
      - 'ci/scripts/run-codebuild/**'
      - '.github/workflows/test-run-codebuild.yml'
  push:
    branches:
      - master
    paths:
      - 'ci/scripts/run-codebuild/**'

jobs:
  test-script-run-codebuild:
    runs-on: ubuntu-20.04
    name: Test script run-codebuild
    env:
      working-directory: ci/scripts/run-codebuild

    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Setup Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: 16.14.0
      - name: Install dependencies
        run: npm ci
        working-directory: 'ci/scripts/run-codebuild'
      - name: Lint check
        run: npm run lint
        working-directory: 'ci/scripts/run-codebuild'
      - name: Unit tests
        run: npm test
        working-directory: 'ci/scripts/run-codebuild'
