name: Run Semver Action Tests

on:
  pull_request:
    paths:
      - 'actions/next-semver/**'
      - '.github/workflows/test-semver.yml'
  push:
    branches:
      - master
    paths:
      - 'actions/next-semver/**'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: 'actions/next-semver/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'actions/next-semver/package-lock.json'
      - name: Install dependencies
        working-directory: 'actions/next-semver'
        run: npm ci
      - name: Run unit tests
        working-directory: 'actions/next-semver'
        run: npm run test
